### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aantara** [Mrbysco/ThisRocksForge#5]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.1.43

### Mod version

1.2.1

### Java version

1.17+

### Issue Description

I don't have a log specifying this mod as it took me some time to figure out that this was the mod causing the issue.

Included this in a modpack I was developing and running on a dedicated server. When we got around to joining the Nether for the first time, the server crashed. The crash was due to a tick taking too long with little helpful information. In single player, I could join the nether but the chunk loading was horrendously slow. 3-5 minutes per chunk. 

I began the process of removing mods one by one to test and when I got to this one, the nether was fine. Chunks started loading as intended and no longer crashed the server. I have little information to offer other than this. Something in chunk generation, ONLY in the nether. We tested all other dimensions and had no issues. I noticed no lag in other dimensions and the rocks and sticks seemed to be generating just fine in the overworld.

**Comment by Mrbysco** [comment]
Uploaded a new version to CurseForge that should fix the nether issues
