### ISSUE TITLE
[Suggestion]: There needs to be a config so you can disable sticks or pebbles, or frequency of them spawning

### ISSUE THREAD

**Issue by lSherozl** [Mrbysco/ThisRocksForge#6]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Title describes what I'm suggesting

**Comment by lSherozl** [comment]
Having sticks appear every few blocks, contibutes a lot to worldgen, and there needs to be a way to disable or cut back on it

**Comment by Mrbysco** [comment]
Everything should be change-able with datapacks already. Setting up configs would mean a lot of work as the placed features are no longer registered in code

**Comment by lSherozl** [comment]
Where is the file path to disable or limit the amount of items spawning?

**Comment by Mrbysco** [comment]
https://github.com/Mrbysco/ThisRocksForge/tree/1.19/src/generated/resources/data/rocks/worldgen/placed_feature
